"""Initial migration

Revision ID: 178e94ca7e5b
Revises: 955f869764ab
Create Date: 2025-01-15 23:06:15.246366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '178e94ca7e5b'
down_revision: Union[str, None] = '955f869764ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_registration', sa.Column('event_registration_user_id', sa.Integer(), nullable=False))
    op.drop_constraint('event_registration_event_egistration_user_id_fkey', 'event_registration', type_='foreignkey')
    op.create_foreign_key(None, 'event_registration', 'user', ['event_registration_user_id'], ['id'])
    op.drop_column('event_registration', 'event_egistration_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_registration', sa.Column('event_egistration_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'event_registration', type_='foreignkey')
    op.create_foreign_key('event_registration_event_egistration_user_id_fkey', 'event_registration', 'user', ['event_egistration_user_id'], ['id'])
    op.drop_column('event_registration', 'event_registration_user_id')
    # ### end Alembic commands ###
