"""Initial migration

Revision ID: 18b570c2efea
Revises: 178e94ca7e5b
Create Date: 2025-02-23 16:26:56.478183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18b570c2efea'
down_revision: Union[str, None] = '178e94ca7e5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('news_image', sa.String(length=255), nullable=False),
    sa.Column('news_text', sa.String(length=5000), nullable=False),
    sa.Column('news_date', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('news_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    # ### end Alembic commands ###
