"""Initial migration

Revision ID: 955f869764ab
Revises: 2576018b7ec1
Create Date: 2025-01-15 22:44:57.324171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '955f869764ab'
down_revision: Union[str, None] = '2576018b7ec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('event_description', sa.String(length=1000), nullable=True))
    op.drop_column('event', 'event_discription')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('event_discription', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_column('event', 'event_description')
    # ### end Alembic commands ###
